version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=ramendb
      - MYSQL_ROOT_PASSWORD=123

  postgres:
    image: postgres:latest
    container_name: postgres-container-ramen
    environment:
      POSTGRES_DB: ramen
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container-ramen
    environment:
      PGADMIN_DEFAULT_EMAIL: gb@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "54321:80"
    depends_on:
      - postgres
